routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth', 'Fauzi']], function() {
    // your routes
    Route::resource('shares', 'ShareController');
    Route::resource('masters','MasterController');
      // More Routes
});
Auth::routes();


Route::get('/', function () {
    return view('welcome');
});
Route::get('/test', function () {
    return view('test');
});




Route::get('/home', 'HomeController@index')->name('home');

app/Master.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Master extends Model
{
  protected $fillable = [

    'share_name_stock',
    'share_price_stock',
    'share_qty_stock',
    'total'  ];
}

app/Http/Controllers/MasterController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Share;
use App\Master;
use DB;

class MasterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


      $masters = Master::all();

      return view('masters.master_index', compact('masters'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('masters.master_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
        'share_name_stock'=>'required',
        'share_price_stock'=> 'required|integer',
        'share_qty_stock' => 'required|integer'
      ]);
      $master = new Master([
        'share_name_stock' => $request->get('share_name_stock'),
        'share_price_stock'=> $request->get('share_price_stock'),
        'share_qty_stock'=> $request->get('share_qty_stock')

      ]);
      $master->save();

      
      return redirect('/masters')->with('success', 'Stock has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $masters = Master::find($id);

        return view('masters.master_edit', compact('masters'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $request->validate([
     'share_name_stock'=>'required',
     'share_price_stock'=> 'required|integer',
     'share_qty_stock' => 'required|integer'
   ]);

   $master = Master::findOrFail($id);
   $master->share_name_stock = $request->get('share_name_stock');
   $master->share_price_stock = $request->get('share_price_stock');
   $master->share_qty_stock = $request->get('share_qty_stock');
   $master->save();

   return redirect('/masters')->with('success', 'Stock has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $master = Master::find($id);
      $master->delete();

      return redirect('/masters')->with('success', 'Stock has been deleted Successfully');
    }
}

resources/views/masters/master_create.blade.php
@extends('test')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Share
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('masters.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Nama Barang *master:</label>
              <input type="text" class="form-control" name="share_name_stock"/>
          </div>
          <div class="form-group">
              <label for="price">Harga Barang *master :</label>
              <input type="text" class="form-control" name="share_price_stock"/>
          </div>
          <div class="form-group">
              <label for="quantity">Kuantitas Barang *master :</label>
              <input type="text" class="form-control" name="share_qty_stock"/>
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@endsection

resources/views/masters/master_edit.blade.php
@extends('test')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Share
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('masters.update', $masters->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="name">Share Name:</label>
          <input type="text" class="form-control" name="share_name_stock" value={{ $masters->share_name_stock }} />
        </div>
        <div class="form-group">
          <label for="price">Share Price :</label>
          <input type="text" class="form-control" name="share_price_stock" value={{ $masters->share_price_stock }} />
        </div>
        <div class="form-group">
          <td for="quantity">Share Quantity:</td>
          <input type="text" class="form-control" name="share_qty_stock" value={{ $masters->share_qty_stock }} />
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/masters/master_index.blade.php
@extends('test')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="jumbotron text-center">
  <h1> <kbd>Contoh CRUD </kbd></h1>
</div>
<button type="button" class="btn btn-primary btn-md" data-toggle="modal"  data-target="#ModalCreate">
    POPUP CREATE
</button>



<!-- Modal HTML Markup -->

<div id="ModalCreate" class="modal fade">
   <div class="modal-dialog" role="document">
     <div class="modal-header" >

        </div>
       <div class="modal-content">
         <div class="card uper">
           <div class="card-header">
             FORM CREATE
           </div>
           <div class="card-body">
             @if ($errors->any())
               <div class="alert alert-danger">
                 <ul>
                     @foreach ($errors->all() as $error)
                       <li>{{ $error }}</li>
                     @endforeach
                 </ul>
               </div><br />
             @endif
               <form method="post" action="{{ route('masters.store') }}">
                 @csrf
                    <!-- Nama -->
                   <div class="form-group">
                       <label for="name">Nama:</label>
                       <input type="text" class="form-control" name="share_name_stock" placeholder="Nama"/>
                   </div>
                    <!-- Harga -->
                   <div class="form-group">
                       <label for="price">Harga :</label>
                       <input type="text" class="form-control" name="share_price_stock" placeholder="Harga" >
                   </div>
                    <!-- Kuantitas -->
                   <div class="form-group">
                       <label for="quantity">Kuantitas:</label>
                       <input type="text" class="form-control" name="share_qty_stock" placeholder="Kuantitas" >


                   </div>
                   <button type="submit" class="btn btn-primary">Add</button>
               </form>


           </div>
         </div>

       </div><!-- /.modal-content -->
   </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"> </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" ></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" ></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css">

<a href="{{ route('masters.create')}}" class="btn btn-danger ">CREATE</a></td>

<div class="uper">
  <table class="table table-bordered">
    <thead>
      <tr>

        <td>Nama Barang</td>
        <td>Harga Barang</td>
        <td>Jumlah Barang Tersedia</td>
      </tr>
    </thead>
    <tbody>
      @foreach($masters as $m)
      <tr>

          <td>{{$m->share_name_stock_stock}}</td>
          <td>{{$m->share_price_stock_stock}}</td>
          <td>{{$m->share_qty_stock_stock}}</td>



      </tr>
      @endforeach
    </tbody>

<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
  @endif

  <table class="table table-bordered">
    <thead>
        <tr>
          <td>ID</td>
          <td>Nama Barang</td>
          <td>Harga Barang</td>
          <td>Jumlah Barang</td>
          <td>Sub total Harga</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
<h3>Tabel Master: (untuk dropDown di tabel Shares)</h3>
    <tbody>
        @foreach($masters as $master)
        <tr>
            <td>{{$master->id}}</td>
            <td>{{$master->share_name_stock}}</td>
            <td>{{$master->share_price_stock}}</td>
            <td>{{$master->share_qty_stock}}</td>
            <td>{{$master->share_qty_stock * $master->share_price_stock}}</td>
            <td><a href="{{ route('masters.edit',$master->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('masters.destroy', $master->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>




@endsection