routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth', 'Fauzi']], function() {
    // your routes
    Route::resource('shares', 'ShareController');
    Route::resource('masters','MasterController');
      // More Routes
});
Auth::routes();


Route::get('/', function () {
    return view('welcome');
});
Route::get('/test', function () {
    return view('test');
});




Route::get('/home', 'HomeController@index')->name('home');

app/Share.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Share extends Model
{
  protected $fillable = [

    'share_name',
    'share_price',
    'share_qty',
    'total'  ];
}

app/Http/Controllers/ShareController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Share;
use App\Master;
use DB;

class ShareController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

      $shares = Share::all();
      $masters = Master::all();


    $shares_ttl = DB::select('select *, sum(share_qty) as ttl_qty, sum(share_price) as ttl_price, (share_price * share_qty) as jml from shares group by share_name');




      return view('shares.index', compact('shares','shares_ttl','masters'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('shares.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
        'share_name'=>'required',
        'share_price'=> 'required|integer',
        'share_qty' => 'required|integer'
      ]);
      $share = new Share([
        'kode_barang' => $request->get(''),
        'share_name' => $request->get('share_name'),
        'share_price'=> $request->get('share_price'),
        'share_qty'=> $request->get('share_qty')

      ]);
      $share->save();

      $master = Master::where('share_name_stock',$request->get('share_name'))->First();
      $master->share_qty_stock = $master->share_qty_stock - $request->get('share_qty');

      $master->save();

      return redirect('/shares')->with('success', 'Barang berhasil ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $share = Share::find($id);

        return view('shares.edit', compact('share'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $request->validate([
     'share_name'=>'required',
     'share_price'=> 'required|integer',
     'share_qty' => 'required|integer'
   ]);

   $share = Share::findOrFail($id);
   $share->share_name = $request->get('share_name');
   $share->share_price = $request->get('share_price');
   $share->share_qty = $request->get('share_qty');
   $share->save();

   return redirect('/shares')->with('success', 'Barang berhasil diubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $share = Share::find($id);
            $master = Master::where('share_name_stock',$share->share_name)->First();

      $master->share_qty_stock = $master->share_qty_stock + $share->share_qty;
      $master->save();
      $share->delete();



      return redirect('/shares')->with('success', 'Barang berhasil dihapus');
    }
}

resources/views/shares/create.blade.php
@extends('test')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Share
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('shares.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Nama Barang:</label>
              <input type="text" class="form-control" name="share_name"/>
          </div>
          <div class="form-group">
              <label for="price">Harga Barang :</label>
              <input type="text" class="form-control" name="share_price"/>
          </div>
          <div class="form-group">
              <label for="quantity">Kuantitas Barang:</label>
              <input type="text" class="form-control" name="share_qty"/>
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@endsection

resources/views/shares/edit.blade.php
@extends('test')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Share
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('shares.update', $share->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="name">Share Name:</label>
          <input type="text" class="form-control" name="share_name" value={{ $share->share_name }} />
        </div>
        <div class="form-group">
          <label for="price">Share Price :</label>
          <input type="text" class="form-control" name="share_price" value={{ $share->share_price }} />
        </div>
        <div class="form-group">
          <td for="quantity">Share Quantity:</td>
          <input type="text" class="form-control" name="share_qty" value={{ $share->share_qty }} />
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/shares/index.blade.php
@extends('test')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="jumbotron text-center">
  <h1> <kbd>Contoh CRUD </kbd></h1>
</div>
<button type="button" class="btn btn-primary btn-md" data-toggle="modal"  data-target="#ModalCreate">
    POPUP CREATE
</button>



<!-- Modal HTML Markup -->

<div id="ModalCreate" class="modal fade">
   <div class="modal-dialog" role="document">
     <div class="modal-header" >

        </div>
       <div class="modal-content">
         <div class="card uper">
           <div class="card-header">
             FORM CREATE
           </div>
           <div class="card-body">
             @if ($errors->any())
               <div class="alert alert-danger">
                 <ul>
                     @foreach ($errors->all() as $error)
                       <li>{{ $error }}</li>
                     @endforeach
                 </ul>
               </div><br />
             @endif
               <form method="post" action="{{ route('shares.store') }}">
                 @csrf
                    <!-- Nama -->
                   <div class="form-group">
                       <label for="name">Nama:</label>
                       <input type="text" class="form-control" name="share_name" placeholder="Nama"/>
                   </div>
                    <!-- Harga -->
                   <div class="form-group">
                       <label for="price">Harga :</label>
                       <input type="text" class="form-control" name="share_price" placeholder="Harga" >
                   </div>
                    <!-- Kuantitas -->
                   <div class="form-group">
                       <label for="quantity">Kuantitas:</label>
                       <input type="text" class="form-control" name="share_qty" placeholder="Kuantitas" >


                   </div>
                   <button type="submit" class="btn btn-primary">Add</button>
               </form>


           </div>
         </div>

       </div><!-- /.modal-content -->
   </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"> </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" ></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" ></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css">

<a href="{{ route('shares.create')}}" class="btn btn-danger ">CREATE</a></td>

<div class="uper">
  <table class="table table-bordered">
    <thead>
      <tr>

        <td>Nama Barang</td>
        <td>Harga Barang</td>
        <td>Jumlah Barang Tersedia</td>
      </tr>
    </thead>
    <tbody>
      @foreach($masters as $m)
      <tr>

          <td>{{$m->share_name_stock}}</td>
          <td>Rp.{{$m->share_price_stock}}</td>
          <td>{{$m->share_qty_stock}}</td>



      </tr>
      @endforeach
    </tbody>

<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
  @endif

  <table class="table table-bordered">
    <thead>
        <tr>

          <td>Nama Barang</td>
          <td>Harga Barang</td>
          <td>Jumlah Barang</td>
          <td>Sub total Harga</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
<h3>Transaksi</h3>
    <tbody>
        @foreach($shares as $share)
        <tr>



            <td>{{$share->share_name}}</td>
            <td>Rp.{{$share->share_price}}</td>
            <td>{{$share->share_qty}}</td>
            <td>Rp.{{$share->share_qty * $share->share_price}}</td>
            <td><a href="{{ route('shares.edit',$share->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('shares.destroy', $share->id )}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>



<h3>Summary</h3>
  <div class="uper">

    <table class="table table-bordered">
      <thead>
          <tr>
            <td> Nama Barang </td>
            <td>Sub Total Barang</td>
            <td>Sub Total Harga</td>
            <td>Total</td>

          </tr>
      </thead>
      <tbody>
          @foreach($shares_ttl as $ttl)
          <tr>
              <td>{{$ttl->share_name}}</td>
              <td>{{$ttl->ttl_qty}}</td>
              <td>Rp.{{$ttl->ttl_price}}</td>
              <td>Rp.{{$ttl->ttl_qty * $ttl->ttl_price}}</td>

          </tr>
          @endforeach
          <table class="table table-bordered">
            <thead>

                <tr>
                  <td>  </td>
                </tr>

            </thead>


      </tbody>
    </table>
  <div>
@endsection